name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - master # Replace with your default branch

permissions:
  id-token: write 
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and export
        run: npm run export

      - name: Download GitHub Pages artifact
        uses: actions/download-artifact@v4 # Ensure you're using v4 or later
        with:
          name: github-pages # This must exactly match the name used for upload
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages # This must exactly match the name used for download